import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Providers } from "@/lib/providers";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demo NextJS",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <Providers>
    <html lang="en">
      <body className={font.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  </Providers>
);

export default RootLayout;
